on:
  push:
    branches:
      - stg
  workflow_dispatch:

name: Push to Amazon ECR for Stg

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR - migration
      id: build-image-migration
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: sprig
        IMAGE_TAG: stg-migration-${{ github.sha }}
        BUILD_EXTRA: --target migration
      run: |
        readonly IMAGE="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        docker build $BUILD_EXTRA -t $IMAGE .
        docker push $IMAGE
        echo "::set-output name=image::$IMAGE"

    - name: Build, tag, and push image to Amazon ECR - api
      id: build-image-api
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: sprig
        IMAGE_TAG: stg-api-${{ github.sha }}
        BUILD_EXTRA: --build-arg cmd_help_dir=/usr/local/share/help --build-arg work_dir=/usr/local/src --target prod
      run: |
        readonly IMAGE="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        docker build $BUILD_EXTRA -t $IMAGE .
        docker push $IMAGE
        echo "::set-output name=image::$IMAGE"
